In [394]:
import numpy as np

In [395]:
vector = np.array([2,6,8])

In [396]:
print(vector.shape)

(3,)


In [397]:
matrix = np.array([[10,20,30],[70,80,90],[110,120,130],[170,180,200]])
print(matrix.shape)

(4, 3)


In [398]:
matrix = np.array([[10,20,30],[70,80,90],[110,120,130],[170,180,200]])

In [399]:
print(matrix.shape) #dimensions

(4, 3)


In [400]:
import numpy as np 
vector = np.array([2,6,8])
matrix = np.array([[10,20,30],[70,80,90],[110,120,130],[170,180,200]])

vector_shape = vector.shape
matrix_shape = matrix.shape

print(vector_shape)
print(matrix_shape)

(3,)
(4, 3)


In [401]:
import numpy as np 
vector = np.array([2,6,8])
matrix = np.array([[10,20,30],[70,80,90],[110,120,130],[170,180,200]])

vector_shape = vector.shape
matrix_shape = matrix.shape

print(vector_shape)
print(matrix_shape)

(3,)
(4, 3)


In [402]:
import numpy as np 
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",")
print(world_alcohol)

[[      nan       nan       nan       nan       nan]
 [1.986e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.000e-01]
 ...
 [1.986e+03       nan       nan       nan 2.540e+00]
 [1.987e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.150e+00]]


In [403]:
import numpy as np 
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",")
world_alcohol_dtype = world_alcohol.dtype

In [404]:
import numpy as np 
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",")
world_alcohol_dtype = world_alcohol.dtype
print(world_alcohol_dtype)

float64


In [405]:
import numpy as np 
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype = "U75",skip_header=1 )
print(world_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [406]:
vector = np.array([10,20,30])
print(vector[1])

20


In [407]:
import numpy as np
matrix = np.array([[50,60,70],[80,90,100]])
matrix[0,2]  


70

In [408]:
import numpy as np
matrix = np.array([[50,60,70],[80,90,100]])
matrix[0,2]  

70

In [409]:
list_of_lists = [[50,60,70],[80,90,100]]
list_of_lists[0][2]

70

In [410]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype = "U75",skip_header = 1)
ivoire_1985 = world_alcohol[2,4]
print(ivoire_1985)


1.62


In [411]:
import numpy as np 
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype = "U75",skip_header = 1)
second_country = world_alcohol[1,2]
print(second_country)

Uruguay


  # EXTRAIRE UN VECTEUR DE VALEUR DEPUIS UN TABLEAU NUMPY 

In [412]:
import numpy as np 
vector = np.array([10,20,30,40])
vector[1:3]

array([20, 30])

In [413]:
matrix = np.array([[50,60,70],[80,90,100],[110,120,130]])
print(matrix)

[[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]


In [414]:
matrix[:,1] #affiche tous les élements d'une colonne 

array([ 60,  90, 120])

In [415]:
matrix[2,:] # afficher tous les élements d'une ligne 

array([110, 120, 130])

In [416]:
matrix[1,:] #affiche tous les élements d'une ligne 

array([ 80,  90, 100])

In [417]:
matrix[:,0] #affiche les éléments d'une colonne      

array([ 50,  80, 110])

In [418]:
matrix[0,:]

array([50, 60, 70])

In [419]:
matrix[:,2]

array([ 70, 100, 130])

In [420]:
matrix[1:2]

array([[ 80,  90, 100]])

In [421]:
matrix[1:3,1]

array([ 90, 120])

In [422]:
import numpy as np 
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype = "U75")
print(world_alcohol)
  

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [423]:
countries = world_alcohol[:,2]

In [424]:
print(countries)

['Country' 'Viet Nam' 'Uruguay' ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [425]:
alcohol_consumption = world_alcohol[:,4]
print(alcohol_consumption)

['Display Value' '0' '0.5' ... '2.54' '0' '5.15']


In [426]:
print(matrix)

[[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]


In [427]:
matrix[:,0:2]

array([[ 50,  60],
       [ 80,  90],
       [110, 120]])

In [428]:
matrix[1:3,:]

array([[ 80,  90, 100],
       [110, 120, 130]])

In [429]:
first_two_columns = world_alcohol[:,0:2]
print(first_two_columns)

[['Year' 'WHO region']
 ['1986' 'Western Pacific']
 ['1986' 'Americas']
 ...
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]


In [430]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype = "U75")
first_ten_years = world_alcohol[0:10,:]
print(first_ten_years)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']]


In [431]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype = "U75")
first_ten_rows = world_alcohol[0:10,:]
print(first_ten_rows)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']]


In [432]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype = "U75",skip_header = 1)
first_twenty_regions= world_alcohol[0:20,1:3]
print(first_twenty_regions) 

[['Western Pacific' 'Viet Nam']
 ['Americas' 'Uruguay']
 ['Africa' "Cte d'Ivoire"]
 ['Americas' 'Colombia']
 ['Americas' 'Saint Kitts and Nevis']
 ['Americas' 'Guatemala']
 ['Africa' 'Mauritius']
 ['Africa' 'Angola']
 ['Americas' 'Antigua and Barbuda']
 ['Africa' 'Nigeria']
 ['Africa' 'Botswana']
 ['Americas' 'Guatemala']
 ['Western Pacific' "Lao People's Democratic Republic"]
 ['Eastern Mediterranean' 'Afghanistan']
 ['Western Pacific' 'Viet Nam']
 ['Africa' 'Guinea-Bissau']
 ['Americas' 'Costa Rica']
 ['Africa' 'Seychelles']
 ['Europe' 'Norway']
 ['Africa' 'Kenya']]


In [433]:
import numpy as np
vector = np.array([10,20,25,50])
vector == 25 #comparaison numpy

array([False, False,  True, False])

In [434]:
matrix= np.array([[5,10,20],[25,30,35],[40,45,50]])

In [435]:
matrix == 50

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [436]:
world_alcohol = np.genfromtxt("world_alcohol.csv", dtype ="U75", delimiter=",",skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [437]:
world_alcohol[:,2]

array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], dtype='<U75')

In [438]:
world_alcohol[:,2] == "Canada"

array([False, False, False, ..., False, False, False])

In [439]:
counries_canada = (world_alcohol[:,2] == "Canada" )
counries_canada

array([False, False, False, ..., False, False, False])

In [440]:
years_1984 = (world_alcohol[:,0] == "1984")
years_1984

array([False, False, False, ..., False, False, False])

In [441]:
import numpy as np
vector = np.array([5,10,15,20])
equal_to_ten = (vector == 10) #retourne un vecteur de booleens
print(vector[equal_to_ten])

[10]


In [442]:
matrix= np.array([[5,10,20],[25,30,35],[40,45,50]])
matrix

array([[ 5, 10, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [443]:
matrix= np.array([[5,10,20],[23,25,35],[40,45,50]])
second_column_25 = (matrix[:,1] == 25)
print(matrix[second_column_25,:])

[[23 25 35]]


In [444]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", dtype ="U75", delimiter=",",skip_header=1)
country_is_algeria = (world_alcohol[:,2] == "Algeria")
country_algeria = world_alcohol[country_is_algeria]
print(country_algeria)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [445]:
#world_alcohol = np.genfromtxt("world_alcohol.csv", dtype ="U75", delimiter="," skip_header= 1)

In [446]:
print(world_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [447]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", dtype ="U75", delimiter=",",skip_header=1)
years_1984 = (world_alcohol[:,0] == "1984")
print(world_alcohol[years_1984])

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


In [448]:
vector = np.array([5,10,20,30,40])
vector 

array([ 5, 10, 20, 30, 40])

In [449]:
equal_to_five_or_ten = (vector == 10) | (vector == 5)
print(equal_to_five_or_ten)

[ True  True False False False]


In [450]:
is_algeria_and_1986 = (world_alcohol[:,2] == "Algeria")  & (world_alcohol[:,0] == "1986")
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986]
print(rows_with_algeria_and_1986)

[['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']]


In [451]:
vector = np.array([20,10,5,30,40])
equal_to_five_or_ten = (vector == 10) | (vector == 5)
print(equal_to_five_or_ten)

[False  True  True False False]


In [452]:
vector[equal_to_five_or_ten] = 50
print(vector)

[20 50 50 30 40]


In [453]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [454]:
second_column_25 = matrix[:,1] == 25 
print(second_column_25)

[False  True False]


In [455]:
matrix[second_column_25] = 10
print(matrix)

[[ 5 10 15]
 [10 10 10]
 [35 40 45]]


In [456]:
world_alcohol = np.genfromtxt("world_alcohol.csv", dtype ="U75", delimiter=",",skip_header=1)
world_alcohoh_2 = world_alcohol

In [457]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", dtype ="U75", delimiter=",")
world_alcohol_2 = world_alcohol
years_1986 = world_alcohol_2[:,0] == '1986'
world_alcohol_2[years_1986,0] = '2018'
print(world_alcohol_2)


[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['2018' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


In [458]:
country = world_alcohol_2[:,2] == 'Cameroon'
print(world_alcohol_2[country])

[['1985' 'Africa' 'Cameroon' 'Spirits' '0.01']
 ['1984' 'Africa' 'Cameroon' 'Wine' '0.08']
 ['2018' 'Africa' 'Cameroon' 'Wine' '0.08']
 ['1987' 'Africa' 'Cameroon' 'Other' '3.97']
 ['2018' 'Africa' 'Cameroon' 'Beer' '2.45']
 ['1989' 'Africa' 'Cameroon' 'Other' '4.08']
 ['1987' 'Africa' 'Cameroon' 'Spirits' '0.02']
 ['1985' 'Africa' 'Cameroon' 'Wine' '0.09']
 ['1985' 'Africa' 'Cameroon' 'Other' '3.61']
 ['2018' 'Africa' 'Cameroon' 'Other' '3.96']
 ['1984' 'Africa' 'Cameroon' 'Spirits' '0.01']
 ['1987' 'Africa' 'Cameroon' 'Beer' '2.39']
 ['1989' 'Africa' 'Cameroon' 'Beer' '2.11']
 ['1989' 'Africa' 'Cameroon' 'Wine' '0.13']
 ['2018' 'Africa' 'Cameroon' 'Spirits' '0.01']
 ['1989' 'Africa' 'Cameroon' 'Spirits' '0.04']
 ['1985' 'Africa' 'Cameroon' 'Beer' '2.5']
 ['1984' 'Africa' 'Cameroon' 'Other' '3.55']
 ['1987' 'Africa' 'Cameroon' 'Wine' '0.12']
 ['1984' 'Africa' 'Cameroon' 'Beer' '2.33']]


In [515]:
is_value_empty = world_alcohol[:,4] == ''
world_alcohol[is_value_empty, 4] = '0'
print(world_alcohol)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [510]:
vector = np.array(["5","10","20"])
vector = vector.astype(float)
vector

array([ 5., 10., 20.])

In [533]:
#alcohol_consumption = world_alcohol[:,4]
#alcohol_consumption = alcohol_consumption.astype(float)
#print(alcohol_consumption)

In [503]:
vector = np.array([5,10,20,30])
vector.sum()             

65

In [473]:
vector.mean()

16.25

In [474]:
vector.max()

30

In [475]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix)
matrix.sum(axis=1)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([ 30,  75, 120])

In [476]:
matrix.sum(axis=0)

array([60, 75, 90])

In [531]:
#total_alcohol = alcohol_consumption.sum()
#total_alcohol

In [532]:
#average_alcohol_consumption = alcohol_consumption.mean()
#print(average_alcohol_consumption)

In [479]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.csv", dtype ="U75", delimiter=",")
canada_1986 = (world_alcohol[:,0] == "1986") & (world_alcohol[:,2] == "Canada")                   
canada_1986 = world_alcohol[canada_1986]
print(canada_1986)

[['1986' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']]


In [534]:
canada_alcohol = canada_1986[:,4]
print(canada_alcohol)

['0' '3.11' '4.87' '1.33']


In [535]:
canada_alcohol = canada_alcohol.astype(float)
print(canada_alcohol)

[0.   3.11 4.87 1.33]


In [483]:
canada_alcohol = canada_alcohol.astype(float)
total_canada_drinking = canada_alcohol.sum()
print(total_canada_drinking)

9.31


In [484]:
totals = {}
is_year = world_alcohol[:,0] == "1989"
year = world_alcohol[is_year,:]
countries = world_alcohol[:,2]
#print(year / countries)

In [485]:
for country in countries: 
    is_country = year[:,2] == country
    country_consumption = year[is_country,:]
    alcohol_column = country_consumption[:,4]
    is_empty = alcohol_column == ''
    alcohol_column[is_empty] = "0"
    alcohol_column = alcohol_column.astype(float)
    totals[country] = alcohol_column.sum()
    
print(totals)

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

{'Country': 0.0, 'Viet Nam': 0.16, 'Uruguay': 7.4399999999999995, "Cte d'Ivoire": 2.2, 'Colombia': 6.960000000000001, 'Saint Kitts and Nevis': 4.65, 'Guatemala': 2.47, 'Mauritius': 3.54, 'Angola': 2.28, 'Antigua and Barbuda': 4.69, 'Nigeria': 6.74, 'Botswana': 4.63, "Lao People's Democratic Republic": 5.95, 'Afghanistan': 0.0, 'Guinea-Bissau': 2.67, 'Costa Rica': 5.3999999999999995, 'Seychelles': 3.3000000000000003, 'Norway': 5.08, 'Kenya': 2.82, 'Myanmar': 0.16, 'Romania': 8.41, 'Turkey': 0.72, 'Comoros': 0.10999999999999999, 'Tunisia': 0.95, 'United Kingdom of Great Britain and Northern Ireland': 9.99, 'Bahrain': 4.89, 'Italy': 10.899999999999999, 'Sierra Leone': 4.380000000000001, 'Micronesia (Federated States of)': 0.0, 'Mauritania': 0.02, 'Russian Federation': 5.35, 'Egypt': 0.42000000000000004, 'Sweden': 7.47, 'Qatar': 1.4500000000000002, 'Burkina Faso': 3.99, 'Austria': 13.9, 'Czech Republic': 13.009999999999998, 'Ukraine': 5.32, 'China': 3.33, 'Lithuania': 0.0, 'Zimbabwe': 4.92

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]
