## mon premier code python

In [19]:
print('bonjour tout le monde')

bonjour tout le monde


In [20]:
import numpy as np

In [21]:
import numpy as np 

In [22]:
vector = np.array([34,17,6])

In [23]:
print(vector)

[34 17  6]


In [24]:
matrix = np.array([[2,4,6], [20,23,26],[26,70,50]])

In [25]:
matrix = np.array([[2,4,6], [20,23,26],[26,70,50]])

In [26]:
print(matrix)

[[ 2  4  6]
 [20 23 26]
 [26 70 50]]


In [27]:
import numpy as np 

In [28]:
import numpy as np

In [29]:
vector = np.array([10,8,9])
matrix = np.array ([[100,101,806],[1000,2000,3000],[18,19,20]])

In [31]:
vector = np.array([10,8,9])
matrix = np.array ([[100,101,806],[1000,2000,3000],[18,19,20]])

In [ ]:
import numpy as np
vector = np.array([10,8,9])
matrix = np.array ([[100,101,806]],[1000,2000,3000],[18,19,20])

In [14]:
import numpy as np
vector = np.array([10,8,9])
matrix = np.array ([[100,101,806],[1000,2000,3000],[18,19,20]])

In [16]:
print(vector)
print(matrix)

[10  8  9]
[[ 100  101  806]
 [1000 2000 3000]
 [  18   19   20]]


In [13]:
print(vector)
print(matrix)

[10  8  9]
[[ 2  4  6]
 [20 23 26]
 [26 70 50]]
